<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Sign in</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet"
        <link rel="stylesheet" href="/css/styles.css">
    </head>
    <body>

        <!-- Splash screen -->
        <section id="page-splash" class="page-splash">
            <div class="d-flex justify-content-center">
                <div class="mx-3">
                    <form id="login-form">
                        <h3>Вход</h3>
                        <input type="text" name="email" class="form-control mb-1" placeholder="email">
                        <input type="password" name="password" class="form-control mb-1" placeholder="Пароль">
                        <button type="submit" href="/" class="btn btn-outline-primary btn-block"> <a href="/">Войти</a></button>
                        <a href="/registration">Registration</a>
                    </form>
                </div>
            </div>

        </section>
    </body>
</html>

<script src="/js/login.js"></script>
